version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - "/home/marek/PycharmProjects/cargo/app:/app:ro"
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      - redis
      - db

  state-reporter:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.reporter
    volumes:
      - "/home/marek/PycharmProjects/cargo/app:/app:ro"
    env_file:
      - .env
    depends_on:
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --workdir / -A app.tasks:celery worker -l INFO
    volumes:
      - "/home/marek/PycharmProjects/cargo/app:/app:ro"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    expose:
      - 6379

volumes:
#  app:
  postgres_data: